### ISSUE TITLE
Encounterlist Issues and Custom Encounters

### ISSUE THREAD

**Issue by DreamblitzX** [Ashenfactory/nuzlocke-tracker#2]
A lot of the encounter lists seem to need some slight checking over, and the addition of statics. for example, in black/white, several of the early cities are listed, but have no grass or water to get an encounter. there's also no line for the gift monkeys, fossils, or legendaries.   
  
The missing static encounters issue would be mostly solved by adding the ability to add blank rows where the location box is also fillable. this would in general add a lot of versatility to the tool.

**Comment by Ashenfactory** [comment]
Almost a year since this was posted and I've thought about it every time I happened to look at the project.
I finally sat down this week have now added the abillity to for users to insert their own custom encounters to a given game. The encounter lists could still do with a little more scrutiny, no doubt, which I'll hopefully be able to afford them sooner rather than later.
